### ISSUE TITLE
Doesn't work!

### ISSUE THREAD

**Issue by hodkash** [QAInsights/perfGPT#33]
Sounds like a great tool, but when tried to upload 13MB and even 2MB file I get 413 Request Entity Too Large...

**Comment by QAInsights** [comment]
@hodkash The maximum file size is 1MiB.

**Comment by pakhilov** [comment]
On average, my K6 CSV file report tends to exceed 500 megabytes in size.

**Comment by QAInsights** [comment]
I understand your requirements. OpenAI consumes thousands of tokens for a 500 MB file. Could you please clone this repo and configure your own OpenAI token and run it? We will also test it locally and try to increase the file limit size. @pakhilov @Ruturaj123

**Comment by QAInsights** [comment]
Closing this as no response received.
