### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by Shivakumard0130** [QAInsights/perfGPT#34]
Used 10MB Raw result.

**Comment by QAInsights** [comment]
@Shivakumard0130 Please share more details. The maximum size is 10 MiB not MB.

**Comment by Shivakumard0130** [comment]
Yes, I used  19,151,233 bytes RAWData file to get the result.

**Comment by Ruturaj123** [comment]
Hey @Shivakumard0130 , 19,151,233 bytes is roughly 18MiB. Upload file size limit is 10MiB.

**Comment by Shivakumard0130** [comment]
Thank you...
