### ISSUE TITLE
Upload button redirects to error page

### ISSUE THREAD

**Issue by jagannathalur** [QAInsights/perfGPT#38]
![image](https://user-images.githubusercontent.com/126662913/223307113-dbd371d1-8665-4127-8faa-0fdff50a2beb.png)

**Comment by QAInsights** [comment]
Thanks @jagannathalur will look into it.

**Comment by QAInsights** [comment]
@jagannathalur Could you please let me know when did you sign up in PerfGPT? CC: @Ruturaj123

**Comment by jagannathalur** [comment]
Hi Naveen,
This was at about 10:30am Singapore time,
Regards,
Jagannath

**Comment by QAInsights** [comment]
Thanks @jagannathalur Please let me know when did you actually `sign up` in PerfGPT?
