### ISSUE TITLE
Not opening browse option while clicking on upload button 

### ISSUE THREAD

**Issue by ialiras** [QAInsights/perfGPT#43]

**Comment by QAInsights** [comment]
Could you please let me know which browser? Uploading a file is a client-side activity. Could you please try it on a different browser or update to the latest version? @ialiras

**Comment by ialiras** [comment]
Hi Naveen,

I have faced this issue on chrome browser.but currently it is working fine


Thanks
Irfan

**Comment by QAInsights** [comment]
Thank you. Closing this.
