### ISSUE TITLE
When i try to upload file from the home page it shows error message "Uh! oh!".

### ISSUE THREAD

**Issue by DevanshiPrime** [QAInsights/perfGPT#47]
https://drive.google.com/file/d/1WZ3kLdtbcSOFBiWa39J7bH9j0qrIzh41/view?usp=sharing

**Comment by QAInsights** [comment]
Fixed, please validate @DevanshiPrime

**Comment by DevanshiPrime** [comment]
> Fixed, please validate @DevanshiPrime

@QAInsights Now it's working fine.
